### ISSUE TITLE
Low result on ConditionalQA dataset

### ISSUE THREAD

**Issue by devishree23** [UKPLab/arxiv2024-conditional-reasoning-llms#2]
I am trying to run both Code Prompt and Text prompt approaches using Mistral and Mixtral models on the ConditionalQA Dev dataset. However, I get very low results for both these approaches than what is mentioned in the paper. 

Code prompt results:
<b style="font-weight:normal;" id="docs-internal-guid-72fa7d2d-7fff-bedf-af71-ef914a863f42">
Model | no. of ICL examples | F1 score
-- | -- | --
Mistral | 4 (paper) | 28.26
Mistral | 4 | 2.97
Mixtral | 4 (paper) | 40.88
Mixtral | 1 | 15.79

</b>

Text Prompt results:
<b style="font-weight:normal;" id="docs-internal-guid-d4d85b10-7fff-7d89-29c5-ab94c7106b4d">
Model | no. of ICL examples | F1 score
-- | -- | --
Mistral | 6 (paper) | 28.84
Mistral | 6 | 12.15
Mixtral | 6 (paper) | 46.60
Mixtral | 1 | 19.44

</b>

Could you help identify what the problem could be?

**Comment by HaritzPuerto** [comment]
Dear Devishree,

Thank you for your interest in our work! I am glad you found it interesting and are trying to run it.

Those low results look like a configuration problem on the LLM inference engine. I have updated the repository, and now you should be able to see all prompts and outputs. Hopefully, you can reproduce the numbers with that.

Best,
Haritz

**Comment by jeongmoonwon** [comment]
@devishree23 Hello, I'm experiencing the same issue. Were you able to resolve it?

**Comment by AwsomeCoders007** [comment]
Hi @jeongmoonwon, My apologies for the late reply. No, I couldn't solve the issue. The authors have uploaded the output of their experiments. I decided to use the values presented in the paper as they are for comparison purposes.
